### ISSUE TITLE
If a molecule has electric charge , some shingles have empty smiles

### ISSUE THREAD

**Issue by mohammad-saber** [reymond-group/map4#12]
Hi, thank you for sharing your great work.

I have tried MAP for a molecule with electric charge as below:

```
smile = '[I-].CC[N+](CC)(CC)c1ccccc1'
mol = Chem.MolFromSmiles(smile)
radius = 2
nBits = 2048

# set "is_folded=False" & "return_strings=True" to get shingles
MAP_c_s = MAP4Calculator(dimensions=nBits, radius = radius, is_folded=False, return_strings=True)
map_s = MAP_c_s.calculate(mol)   
map_s
```

There are shingles that have empty string, for example:

`b'|100000000|c(c)(c)[N+]'`

As can be seen, left smile is an empty string and topological distance is 100000000. It looks strange to me. I would like to ask if it is designed to be like above or there is no reason for it.

Thank you for your time to read my question.

**Comment by alicecapecchi** [comment]
Hi!
you get such a large distance because you have a disconnection in your SMILES (the "[I-]" fragment). 
you get an empty shingle because one of your molecules (the "[I-]" fragment) has only 1 atom and therefore there are no atom pairs to be formed.
I hope this reply to your question.
Cheers,
Alice

**Comment by mohammad-saber** [comment]
Thanks a lot. I understood it well.
