### ISSUE TITLE
Any plans to have map4 in pip?

### ISSUE THREAD

**Issue by jmahenriques** [reymond-group/map4#3]
First of all, very interesting paper, I'm looking forward to test the performance of map4 myself. Any plans to have it in pip? That would make life a lot easier for those trying to implement it and share it on a notebook (`!pip install map4 --user` is definitely simpler than having users have to create their own virtual env and make their notebooks aware of it). Also, your group's `tmap` conflicts with pip's `tmap`, are there any plans to address this?

Thanks!

**Comment by alicecapecchi** [comment]
Hi João,
thanks! 
I am not sure if I will add map4 to pypi since RDKit and tmap are required and not pip installable. 
However, now you can pip install the git repo directly:  pip install git+https://github.com/reymond-group/map4 (see the updated README).
Regarding the tmap installation conflict, please open an issue in the tmap repo (https://github.com/reymond-group/tmap).
Cheers,
Alice
